In [1]:
import pandas as pd

In [22]:
forestfire_df=pd.read_csv('Amazon_Updated.csv',encoding='ISO-8859-1')

In [23]:
forestfire_df

      Year      State     Month  Forest_Fire
0     1998       Acre   January          0.0
1     1999       Acre   January          0.0
2     2000       Acre   January          0.0
3     2001       Acre   January          0.0
4     2002       Acre   January          0.0
5     2003       Acre   January         10.0
6     2004       Acre   January          0.0
7     2005       Acre   January         12.0
8     2006       Acre   January          4.0
9     2007       Acre   January          0.0
10    2008       Acre   January          0.0
11    2009       Acre   January          0.0
12    2010       Acre   January          1.0
13    2011       Acre   January          0.0
14    2012       Acre   January          0.0
15    2013       Acre   January          0.0
16    2014       Acre   January          0.0
17    2015       Acre   January          1.0
18    2016       Acre   January         12.0
19    2017       Acre   January          0.0
20    1998       Acre  February          0.0
21    1999       Acre  February          0.0
22    2000       Acre  February          0.0
23    2001       Acre  February          0.0
24    2002       Acre  February          1.0
25    2003       Acre  February          0.0
26    2004       Acre  February          3.0
27    2005       Acre  February          0.0
28    2006       Acre  February          0.0
29    2007       Acre  February          5.0
...    ...        ...       ...          ...
6424  2007  Tocantins  November        147.0
6425  2008  Tocantins  November        104.0
6426  2009  Tocantins  November        251.0
6427  2010  Tocantins  November        283.0
6428  2011  Tocantins  November        144.0
6429  2012  Tocantins  November        179.0
6430  2013  Tocantins  November        345.0
6431  2014  Tocantins  November        451.0
6432  2015  Tocantins  November        833.0
6433  2016  Tocantins  November        623.0
6434  2017  Tocantins  November        434.0
6435  1998  Tocantins  December          9.0
6436  1999  Tocantins  December         16.0
6437  2000  Tocantins  December         20.0
6438  2001  Tocantins  December         21.0
6439  2002  Tocantins  December         39.0
6440  2003  Tocantins  December        109.0
6441  2004  Tocantins  December         96.0
6442  2005  Tocantins  December         53.0
6443  2006  Tocantins  December         15.0
6444  2007  Tocantins  December         13.0
6445  2008  Tocantins  December          7.0
6446  2009  Tocantins  December         46.0
6447  2010  Tocantins  December         72.0
6448  2011  Tocantins  December        105.0
6449  2012  Tocantins  December        128.0
6450  2013  Tocantins  December         85.0
6451  2014  Tocantins  December        223.0
6452  2015  Tocantins  December        373.0
6453  2016  Tocantins  December        119.0

[6454 rows x 4 columns]

In [24]:
ls

Amazon_Updated.csv  Location.csv        Weather_Info/       firedata.csv
DataCleaning.py     Untitled.ipynb      amazon.csv*

In [25]:
cd Weather_Info/

/Users/praveenkumar/amazonFires/Weather_Info

In [27]:
ls

Alagoas/  Amapa/    Amazonas/ Bahia/

In [28]:
import os

In [37]:
import glob

In [39]:
glob.glob('/Users/praveenkumar/amazonFires/Weather_Info/*')

['/Users/praveenkumar/amazonFires/Weather_Info/Amazonas',
 '/Users/praveenkumar/amazonFires/Weather_Info/Amapa',
 '/Users/praveenkumar/amazonFires/Weather_Info/Alagoas',
 '/Users/praveenkumar/amazonFires/Weather_Info/Bahia']

In [60]:
Amazonas=[]
Bahia=[]
Alagoas=[]
Amapa=[]
for file in glob.glob('/Users/praveenkumar/amazonFires/Weather_Info/*'):
    for files in glob.glob(file +'/*'):
        for values in glob.glob(files+"/*"):
           
            split=values.split('/')
            print(split[5])
            if split[5]=='Bahia':
                Bahia.append(values)
            elif split[5]=='Alagoas':
                Alagoas.append(values)
            elif split[5]=='Amapa':
                Amapa.append(values)
            elif split[5]=='Amazonas':
                Amazonas.append(values)

Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amazonas
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Amapa
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Alagoas
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia
Bahia

In [65]:
len(Bahia)

201

In [66]:
len(Amazonas)

581

In [67]:
len(Amapa)

56

In [68]:
len(Alagoas)

60

In [69]:
test=Bahia[1]

In [70]:
test

'/Users/praveenkumar/amazonFires/Weather_Info/Bahia/12188_2019-09-07-12-51-22/weatherdata--123-422.csv'

In [71]:
testdata=pd.read_csv(test)

In [72]:
testdata

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature,Precipitation,Wind,Relative Humidity,Solar
1/1/1979,-42.1875,-12.333,1076,28.893,15.199,0.000000,5.835187,0.668331,30.320549,NaN
1/2/1979,-42.1875,-12.333,1076,29.931,16.127,0.003433,6.139468,0.619655,30.821369,NaN
1/3/1979,-42.1875,-12.333,1076,30.864,15.635,0.000000,5.297426,0.558058,30.938013,NaN
1/4/1979,-42.1875,-12.333,1076,31.316,15.412,0.000000,3.111359,0.592251,24.376501,NaN
1/5/1979,-42.1875,-12.333,1076,31.455,15.875,0.000000,2.410816,0.564511,22.232926,NaN
1/6/1979,-42.1875,-12.333,1076,29.203,16.145,0.497818,3.021596,0.606072,21.883441,NaN
1/7/1979,-42.1875,-12.333,1076,27.896,18.210,4.142187,3.552129,0.699785,18.015972,NaN
1/8/1979,-42.1875,-12.333,1076,25.376,17.756,17.317202,2.422633,0.878989,21.865382,NaN
1/9/1979,-42.1875,-12.333,1076,20.216,18.061,51.604802,1.385397,0.941339,2.202356,NaN
1/10/1979,-42.1875,-12.333,1076,19.872,17.469,19.359976,1.803984,0.955475,3.665083,NaN
1/11/1979,-42.1875,-12.333,1076,27.036,17.008,8.074948,3.169953,0.876579,13.540722,NaN
1/12/1979,-42.1875,-12.333,1076,27.433,16.475,2.844429,4.036018,0.813344,24.694763,NaN
1/13/1979,-42.1875,-12.333,1076,26.576,17.644,2.538870,3.103854,0.832850,16.674248,NaN
1/14/1979,-42.1875,-12.333,1076,23.093,17.706,22.467038,3.136053,0.919426,9.232930,NaN
1/15/1979,-42.1875,-12.333,1076,20.390,17.271,53.649300,3.583985,0.951311,4.551356,NaN
1/16/1979,-42.1875,-12.333,1076,20.647,16.395,2.297688,2.830806,0.903635,4.206208,NaN
1/17/1979,-42.1875,-12.333,1076,20.494,17.092,4.852869,2.493101,0.922019,4.041170,NaN
1/18/1979,-42.1875,-12.333,1076,26.505,18.077,12.843703,3.053178,0.868834,20.337970,NaN
1/19/1979,-42.1875,-12.333,1076,26.114,16.955,2.514839,3.746829,0.786359,14.225292,NaN
1/20/1979,-42.1875,-12.333,1076,28.417,17.246,0.480652,4.718910,0.726801,25.969386,NaN
1/21/1979,-42.1875,-12.333,1076,29.467,16.048,0.000000,4.611074,0.644296,30.609401,NaN
1/22/1979,-42.1875,-12.333,1076,29.528,14.768,0.000000,3.009626,0.577246,31.129356,NaN
1/23/1979,-42.1875,-12.333,1076,27.473,16.361,3.520775,2.884205,0.733857,24.330209,NaN
1/24/1979,-42.1875,-12.333,1076,28.086,17.392,3.603175,4.376555,0.819760,24.600319,NaN
1/25/1979,-42.1875,-12.333,1076,28.876,17.198,0.024033,5.713690,0.730082,29.938609,NaN
1/26/1979,-42.1875,-12.333,1076,27.892,17.817,4.504396,4.409966,0.769591,26.964843,NaN
1/27/1979,-42.1875,-12.333,1076,29.019,16.488,2.228163,4.092456,0.740835,28.139903,NaN
1/28/1979,-42.1875,-12.333,1076,27.640,17.637,5.973811,3.608911,0.835553,21.483390,NaN
1/29/1979,-42.1875,-12.333,1076,26.926,18.402,4.395393,2.681636,0.844026,18.672476,NaN
1/30/1979,-42.1875,-12.333,1076,27.775,17.647,7.021808,2.930613,0.832367,13.048086,NaN
...,...,...,...,...,...,...,...,...,...,...
7/2/2014,-42.1875,-12.333,1076,31.524,16.864,0.000000,3.038144,0.486769,20.955699,NaN
7/3/2014,-42.1875,-12.333,1076,31.162,16.433,0.000000,3.320995,0.520133,20.981845,NaN
7/4/2014,-42.1875,-12.333,1076,30.476,15.929,0.001717,3.089339,0.553842,21.024851,NaN
7/5/2014,-42.1875,-12.333,1076,30.473,15.263,0.000000,3.595577,0.599249,20.229180,NaN
7/6/2014,-42.1875,-12.333,1076,27.653,16.623,0.000000,3.401952,0.653005,15.242420,NaN
7/7/2014,-42.1875,-12.333,1076,27.810,16.172,0.000000,3.695980,0.650532,19.645871,NaN
7/8/2014,-42.1875,-12.333,1076,28.738,15.232,0.000000,3.238646,0.675442,19.634964,NaN
7/9/2014,-42.1875,-12.333,1076,31.185,15.880,0.000000,2.023390,0.591167,20.788316,NaN
7/10/2014,-42.1875,-12.333,1076,31.349,16.550,0.000000,2.075176,0.526845,20.000529,NaN
7/11/2014,-42.1875,-12.333,1076,29.533,16.013,0.000000,2.268855,0.566614,15.804859,NaN
7/12/2014,-42.1875,-12.333,1076,31.042,16.529,0.000000,2.789800,0.558065,16.325109,NaN
7/13/2014,-42.1875,-12.333,1076,30.071,17.152,0.000000,3.928464,0.553939,20.894907,NaN
7/14/2014,-42.1875,-12.333,1076,27.659,17.209,0.000000,3.654364,0.609260,11.332073,NaN
7/15/2014,-42.1875,-12.333,1076,29.299,15.958,0.000000,2.861543,0.592507,17.686160,NaN
7/16/2014,-42.1875,-12.333,1076,29.754,16.292,0.000000,2.780263,0.598388,17.868276,NaN
7/17/2014,-42.1875,-12.333,1076,29.386,17.584,0.109863,2.082057,0.591839,8.913230,NaN
7/18/2014,-42.1875,-12.333,1076,29.978,19.861,0.000000,1.956295,0.512637,14.973076,NaN
7/19/2014,-42.1875,-12.333,1076,33.805,17.081,0.000000,1.939492,0.533769,17.550085,NaN
7/20/2014,-42.1875,-12.333,1076,30.463,19.093,0.000000,2.736155,0.529997,15.320461,NaN
7/21/2014,-42.1875,-12.333,1076,29.966,17.577,0.000000,3.870956,0.556377,20.489919,NaN
7/22/2014,-42.1875,-12.333,1076,28.483,18.088,0.000000,4.289060,0.602559,18.089626,NaN
7/23/2014,-42.1875,-12.333,1076,29.172,17.500,0.000000,4.148996,0.604264,21.315998,NaN
7/24/2014,-42.1875,-12.333,1076,30.370,16.548,0.000000,3.435493,0.589428,21.578667,NaN
7/25/2014,-42.1875,-12.333,1076,31.752,16.286,0.000000,2.959990,0.606397,21.098509,NaN
7/26/2014,-42.1875,-12.333,1076,31.027,17.432,0.000000,3.411537,0.576322,21.897702,NaN
7/27/2014,-42.1875,-12.333,1076,31.044,17.071,0.000000,3.283439,0.589436,21.839504,NaN
7/28/2014,-42.1875,-12.333,1076,27.798,18.105,1.215362,3.087145,0.706861,12.660651,NaN
7/29/2014,-42.1875,-12.333,1076,28.905,17.625,0.000000,4.045429,0.614181,21.898322,NaN
7/30/2014,-42.1875,-12.333,1076,23.945,16.706,0.243759,3.054201,0.687141,3.628018,NaN
7/31/2014,-42.1875,-12.333,1076,27.278,17.151,0.202560,2.485381,0.608895,7.353664,NaN

In [79]:
testdata=testdata.iloc[:,:-1].dropna()

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature,Precipitation,Wind,Relative Humidity
1/1/1979,-42.1875,-12.333,1076,28.893,15.199,0.000000,5.835187,0.668331,30.320549
1/2/1979,-42.1875,-12.333,1076,29.931,16.127,0.003433,6.139468,0.619655,30.821369
1/3/1979,-42.1875,-12.333,1076,30.864,15.635,0.000000,5.297426,0.558058,30.938013
1/4/1979,-42.1875,-12.333,1076,31.316,15.412,0.000000,3.111359,0.592251,24.376501
1/5/1979,-42.1875,-12.333,1076,31.455,15.875,0.000000,2.410816,0.564511,22.232926
1/6/1979,-42.1875,-12.333,1076,29.203,16.145,0.497818,3.021596,0.606072,21.883441
1/7/1979,-42.1875,-12.333,1076,27.896,18.210,4.142187,3.552129,0.699785,18.015972
1/8/1979,-42.1875,-12.333,1076,25.376,17.756,17.317202,2.422633,0.878989,21.865382
1/9/1979,-42.1875,-12.333,1076,20.216,18.061,51.604802,1.385397,0.941339,2.202356
1/10/1979,-42.1875,-12.333,1076,19.872,17.469,19.359976,1.803984,0.955475,3.665083
1/11/1979,-42.1875,-12.333,1076,27.036,17.008,8.074948,3.169953,0.876579,13.540722
1/12/1979,-42.1875,-12.333,1076,27.433,16.475,2.844429,4.036018,0.813344,24.694763
1/13/1979,-42.1875,-12.333,1076,26.576,17.644,2.538870,3.103854,0.832850,16.674248
1/14/1979,-42.1875,-12.333,1076,23.093,17.706,22.467038,3.136053,0.919426,9.232930
1/15/1979,-42.1875,-12.333,1076,20.390,17.271,53.649300,3.583985,0.951311,4.551356
1/16/1979,-42.1875,-12.333,1076,20.647,16.395,2.297688,2.830806,0.903635,4.206208
1/17/1979,-42.1875,-12.333,1076,20.494,17.092,4.852869,2.493101,0.922019,4.041170
1/18/1979,-42.1875,-12.333,1076,26.505,18.077,12.843703,3.053178,0.868834,20.337970
1/19/1979,-42.1875,-12.333,1076,26.114,16.955,2.514839,3.746829,0.786359,14.225292
1/20/1979,-42.1875,-12.333,1076,28.417,17.246,0.480652,4.718910,0.726801,25.969386
1/21/1979,-42.1875,-12.333,1076,29.467,16.048,0.000000,4.611074,0.644296,30.609401
1/22/1979,-42.1875,-12.333,1076,29.528,14.768,0.000000,3.009626,0.577246,31.129356
1/23/1979,-42.1875,-12.333,1076,27.473,16.361,3.520775,2.884205,0.733857,24.330209
1/24/1979,-42.1875,-12.333,1076,28.086,17.392,3.603175,4.376555,0.819760,24.600319
1/25/1979,-42.1875,-12.333,1076,28.876,17.198,0.024033,5.713690,0.730082,29.938609
1/26/1979,-42.1875,-12.333,1076,27.892,17.817,4.504396,4.409966,0.769591,26.964843
1/27/1979,-42.1875,-12.333,1076,29.019,16.488,2.228163,4.092456,0.740835,28.139903
1/28/1979,-42.1875,-12.333,1076,27.640,17.637,5.973811,3.608911,0.835553,21.483390
1/29/1979,-42.1875,-12.333,1076,26.926,18.402,4.395393,2.681636,0.844026,18.672476
1/30/1979,-42.1875,-12.333,1076,27.775,17.647,7.021808,2.930613,0.832367,13.048086
...,...,...,...,...,...,...,...,...,...
7/2/2014,-42.1875,-12.333,1076,31.524,16.864,0.000000,3.038144,0.486769,20.955699
7/3/2014,-42.1875,-12.333,1076,31.162,16.433,0.000000,3.320995,0.520133,20.981845
7/4/2014,-42.1875,-12.333,1076,30.476,15.929,0.001717,3.089339,0.553842,21.024851
7/5/2014,-42.1875,-12.333,1076,30.473,15.263,0.000000,3.595577,0.599249,20.229180
7/6/2014,-42.1875,-12.333,1076,27.653,16.623,0.000000,3.401952,0.653005,15.242420
7/7/2014,-42.1875,-12.333,1076,27.810,16.172,0.000000,3.695980,0.650532,19.645871
7/8/2014,-42.1875,-12.333,1076,28.738,15.232,0.000000,3.238646,0.675442,19.634964
7/9/2014,-42.1875,-12.333,1076,31.185,15.880,0.000000,2.023390,0.591167,20.788316
7/10/2014,-42.1875,-12.333,1076,31.349,16.550,0.000000,2.075176,0.526845,20.000529
7/11/2014,-42.1875,-12.333,1076,29.533,16.013,0.000000,2.268855,0.566614,15.804859
7/12/2014,-42.1875,-12.333,1076,31.042,16.529,0.000000,2.789800,0.558065,16.325109
7/13/2014,-42.1875,-12.333,1076,30.071,17.152,0.000000,3.928464,0.553939,20.894907
7/14/2014,-42.1875,-12.333,1076,27.659,17.209,0.000000,3.654364,0.609260,11.332073
7/15/2014,-42.1875,-12.333,1076,29.299,15.958,0.000000,2.861543,0.592507,17.686160
7/16/2014,-42.1875,-12.333,1076,29.754,16.292,0.000000,2.780263,0.598388,17.868276
7/17/2014,-42.1875,-12.333,1076,29.386,17.584,0.109863,2.082057,0.591839,8.913230
7/18/2014,-42.1875,-12.333,1076,29.978,19.861,0.000000,1.956295,0.512637,14.973076
7/19/2014,-42.1875,-12.333,1076,33.805,17.081,0.000000,1.939492,0.533769,17.550085
7/20/2014,-42.1875,-12.333,1076,30.463,19.093,0.000000,2.736155,0.529997,15.320461
7/21/2014,-42.1875,-12.333,1076,29.966,17.577,0.000000,3.870956,0.556377,20.489919
7/22/2014,-42.1875,-12.333,1076,28.483,18.088,0.000000,4.289060,0.602559,18.089626
7/23/2014,-42.1875,-12.333,1076,29.172,17.500,0.000000,4.148996,0.604264,21.315998
7/24/2014,-42.1875,-12.333,1076,30.370,16.548,0.000000,3.435493,0.589428,21.578667
7/25/2014,-42.1875,-12.333,1076,31.752,16.286,0.000000,2.959990,0.606397,21.098509
7/26/2014,-42.1875,-12.333,1076,31.027,17.432,0.000000,3.411537,0.576322,21.897702
7/27/2014,-42.1875,-12.333,1076,31.044,17.071,0.000000,3.283439,0.589436,21.839504
7/28/2014,-42.1875,-12.333,1076,27.798,18.105,1.215362,3.087145,0.706861,12.660651
7/29/2014,-42.1875,-12.333,1076,28.905,17.625,0.000000,4.045429,0.614181,21.898322
7/30/2014,-42.1875,-12.333,1076,23.945,16.706,0.243759,3.054201,0.687141,3.628018
7/31/2014,-42.1875,-12.333,1076,27.278,17.151,0.202560,2.485381,0.608895,7.353664

In [83]:
testdata.describe()

,Date,Longitude,Latitude,Elevation,Max Temperature,Min Temperature,Precipitation,Wind,Relative Humidity,Solar
count,12987.0000,1.298700e+04,12987.0,12987.000000,12987.000000,12987.000000,12987.000000,12987.000000,12987.000000,0.0
mean,-42.1875,-1.233300e+01,1076.0,28.151138,16.136122,2.044228,4.123969,0.669298,19.968930,NaN
std,0.0000,1.776425e-15,0.0,3.459552,2.006614,6.992810,1.379365,0.110215,6.334623,NaN
min,-42.1875,-1.233300e+01,1076.0,15.878000,8.602000,0.000000,0.749786,0.275663,0.000000,NaN
25%,-42.1875,-1.233300e+01,1076.0,26.017000,14.810500,0.000000,3.070548,0.592245,16.452226,NaN
50%,-42.1875,-1.233300e+01,1076.0,28.431000,16.281000,0.082397,4.156325,0.665416,20.726940,NaN
75%,-42.1875,-1.233300e+01,1076.0,30.461000,17.545500,0.561332,5.149483,0.740257,24.271310,NaN
max,-42.1875,-1.233300e+01,1076.0,41.949000,25.155000,127.860322,8.325346,0.969686,32.108673,NaN